# Generated by Django 5.1.2 on 2024-11-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='allreply',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
