# Generated by Django 5.1.2 on 2024-11-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_adminpost_created_alter_allreply_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allreply',
            name='created_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allreply',
            name='last_updated',
            field=models.DateField(),
        ),
    ]
