# Generated by Django 5.1.2 on 2024-11-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_adminpost_created_alter_allreply_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='allreply',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='allreply',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
