# Generated by Django 5.1.2 on 2024-11-12 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_adminpost_created_alter_allreply_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='topicTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dktopic',
            name='topicTheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.topictheme'),
        ),
    ]
