# Generated by Django 5.1.2 on 2024-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_adminpost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
