# Generated by Django 5.1.2 on 2024-11-12 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_adminpost_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpost',
            name='created',
        ),
        migrations.AddField(
            model_name='adminpost',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
