# Generated by Django 5.1.2 on 2024-11-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_adminpost_created_adminpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpost',
            old_name='date',
            new_name='created',
        ),
    ]
