# Generated by Django 5.1.2 on 2024-11-15 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_date_adminpost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
