# Generated by Django 5.1.2 on 2024-12-30 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notePost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.adminpost'),
        ),
    ]
